version: '3.8'

services:
  app:
    image: ghcr.io/migz93/msical:latest
    container_name: msical
    network_mode: bridge
    ports:
      - "5600:5600"
    volumes:
      - ./config:/config
    restart: unless-stopped
